#!/usr/bin/env python3
"""build.py — generate the static pages of nomoreidea.ir.

Single source of truth:
  content/en.json, content/fa.json   UI strings for both languages
  content/projects.json              featured project pages (EN + FA)
  content/site.json                  hidden / pinned repositories
  data/projects.json                 GitHub snapshot (tools/sync_projects.py)
  src/template.html                  page skeleton

Outputs (committed, served by GitHub Pages):
  index.html, fa/index.html          home pages (real HTML in each language)
  projects/<slug>/index.html         featured project pages (+ fa/ copies)
  js/i18n.en.js, js/i18n.fa.js       runtime strings for dynamic UI text
  js/site-config.js, sitemap.xml, 404.html

Run:  python tools/build.py        (needs only the Python standard library)
"""
from __future__ import annotations

import datetime as dt
import hashlib
import html
import json
import os
import re
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SITE = "https://nomoreidea.ir"
NAME_EN = "Mahbod BemaniCham"
NAME_FA = "مهبد بمانی‌چم"
OG_IMAGE = f"{SITE}/images/og-image.jpg"
LOCALES = {"en": "en_US", "fa": "fa_IR"}


def rd(*p):
    with open(os.path.join(ROOT, *p), encoding="utf-8") as f:
        return f.read()


def wr(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def jl(*p):
    return json.loads(rd(*p))


def norm(v):
    if isinstance(v, str):
        return re.sub(r"\s+", " ", v).strip()
    return v


STR = {l: {k: norm(v) for k, v in jl("content", f"{l}.json").items()} for l in ("en", "fa")}
PROJECTS = jl("content", "projects.json")
CFG = jl("content", "site.json")
try:
    SNAP = jl("data", "projects.json")
except OSError:
    SNAP = {"repos": [], "stats": {}}

# ───────────────────────── helpers ─────────────────────────
_h = {}


def asset(path):
    """/css/site.css -> /css/site.css?v=<hash> (cache busting)."""
    if path not in _h:
        with open(os.path.join(ROOT, path.lstrip("/")), "rb") as f:
            _h[path] = hashlib.sha1(f.read()).hexdigest()[:8]
    return f"{path}?v={_h[path]}"


def esc(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def prefix(lang):
    return "" if lang == "en" else "/fa"


def home_url(lang):
    return f"{SITE}/" if lang == "en" else f"{SITE}/fa/"


def sl(slug):
    return slug.lower()


def proj_url(lang, slug):
    return f"{SITE}{prefix(lang)}/projects/{sl(slug)}/"


def last_change():
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%cs", "--", "src", "content", "tools/build.py"],
            cwd=ROOT, stderr=subprocess.DEVNULL, text=True).strip()
        if out:
            return out
    except Exception:  # noqa: BLE001
        pass
    return dt.date.today().isoformat()


LASTMOD = last_change()
SYNC_DAY = (SNAP.get("syncedAt") or "")[:10]
HOME_LASTMOD = max(LASTMOD, SYNC_DAY) if SYNC_DAY else LASTMOD

LANG_COLORS = {"Python": "#3572A5", "C++": "#f34b7d", "C": "#8a8a8a", "C#": "#178600", "VHDL": "#adb2cb",
               "Verilog": "#b2b7f8", "HTML": "#e34c26", "CSS": "#663399", "JavaScript": "#f1e05a",
               "TypeScript": "#3178c6", "MATLAB": "#e16737", "Java": "#b07219", "Shell": "#89e051",
               "Arduino": "#bd79d8", "Assembly": "#6E4C13", "QML": "#44a51c", "PHP": "#4F5D95"}


def rel_time(iso, lang):
    """Static HTML shows an absolute date (stable between builds); JS swaps in 'x days ago'."""
    return (iso or "")[:10]


# ───────────────────────── runtime JS ─────────────────────────
RUNTIME = r"""
function t(key) {
  const lang = document.documentElement.lang === "fa" ? "fa" : "en";
  return (I18N[lang] && I18N[lang][key]) || (I18N.en && I18N.en[key]) || key;
}
function fmt(key, vars) {
  let s = t(key);
  Object.keys(vars || {}).forEach(k => { s = s.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]); });
  return s;
}
/* Each language has its own URL (/ and /fa/), so switching = navigating. */
function setLang(lang) {
  const cur = document.documentElement.lang === "fa" ? "fa" : "en";
  if (lang !== "fa" && lang !== "en") lang = "en";
  if (lang === cur) return;
  location.href = (lang === "fa" ? "/fa/" : "/") + location.hash;
}
"""


def write_runtime():
    for lang in ("en", "fa"):
        d = {k: v for k, v in STR[lang].items()}
        data = {"en": {}, "fa": {}}
        data[lang] = d
        wr(f"js/i18n.{lang}.js",
           "/* generated by tools/build.py — edit content/*.json instead */\n"
           f"const I18N = {json.dumps(data, ensure_ascii=False)};\n{RUNTIME}")
    wr("js/site-config.js",
       "/* generated by tools/build.py from content/site.json */\n"
       f"window.SITE = {json.dumps(CFG)};\n")


# ───────────────────────── head ─────────────────────────
BOOT = ('<script>(function(){document.documentElement.classList.add("js");'
        'try{var t=localStorage.getItem("site_theme");if(t)document.documentElement.setAttribute("data-theme",t);}'
        'catch(e){}})();</script>')


def head(lang, title, desc, canonical, alternates, jsonld, og_type="website", robots="index, follow",
         og_alt=None, preload=True):
    s = STR[lang]
    other = "fa" if lang == "en" else "en"
    p = []
    p.append('<meta charset="UTF-8" />')
    p.append('<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />')
    p.append(f"<title>{esc(title)}</title>")
    p.append(f'<meta name="description" content="{esc(desc)}" />')
    p.append(f'<meta name="robots" content="{robots}, max-image-preview:large" />')
    p.append(f'<meta name="author" content="{NAME_EN}" />')
    p.append(f'<link rel="canonical" href="{canonical}" />')
    for hl, url in alternates:
        p.append(f'<link rel="alternate" hreflang="{hl}" href="{url}" />')
    p.append(f'<meta property="og:site_name" content="{NAME_EN}" />')
    p.append(f'<meta property="og:type" content="{og_type}" />')
    p.append(f'<meta property="og:title" content="{esc(title)}" />')
    p.append(f'<meta property="og:description" content="{esc(s["og_desc"] if og_type == "website" and canonical.endswith("/") and "/projects/" not in canonical else desc)}" />')
    p.append(f'<meta property="og:url" content="{canonical}" />')
    p.append(f'<meta property="og:locale" content="{LOCALES[lang]}" />')
    p.append(f'<meta property="og:locale:alternate" content="{LOCALES[other]}" />')
    p.append(f'<meta property="og:image" content="{OG_IMAGE}" />')
    p.append('<meta property="og:image:width" content="1200" />')
    p.append('<meta property="og:image:height" content="630" />')
    p.append(f'<meta property="og:image:alt" content="{esc(og_alt or title)}" />')
    p.append('<meta name="twitter:card" content="summary_large_image" />')
    p.append(f'<meta name="twitter:title" content="{esc(title)}" />')
    p.append(f'<meta name="twitter:description" content="{esc(desc)}" />')
    p.append(f'<meta name="twitter:image" content="{OG_IMAGE}" />')
    p.append('<meta name="color-scheme" content="dark light" />')
    p.append('<meta name="theme-color" content="#141824" />')
    p.append('<link rel="icon" href="/favicon.svg" type="image/svg+xml" />')
    p.append('<link rel="icon" href="/favicon.ico" sizes="48x48" />')
    p.append('<link rel="apple-touch-icon" href="/icons/icon-180.png" />')
    p.append('<link rel="manifest" href="/manifest.webmanifest" />')
    p.append(BOOT)
    if preload:
        fonts = (["inter-latin-wght-normal", "space-grotesk-latin-wght-normal"] if lang == "en"
                 else ["vazirmatn-arabic-400-normal", "vazirmatn-arabic-700-normal"])
        for f in fonts:
            p.append(f'<link rel="preload" href="/fonts/{f}.woff2" as="font" type="font/woff2" crossorigin />')
    for css in ("/css/fonts.css", "/css/tokens.css", "/css/site.css"):
        p.append(f'<link rel="stylesheet" href="{asset(css)}" />')
    p.append(f'<script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>')
    return "\n".join(p)


def person(lang):
    return {
        "@type": "Person", "@id": f"{SITE}/#person",
        "name": NAME_EN, "alternateName": [NAME_FA],
        "url": f"{SITE}/", "image": f"{SITE}/images/mahbod.jpg",
        "jobTitle": "Electrical Engineering Student",
        "description": STR["en"]["meta_desc"],
        "address": {"@type": "PostalAddress", "addressLocality": "Tehran", "addressCountry": "IR"},
        "alumniOf": {"@type": "CollegeOrUniversity", "name": "Amirkabir University of Technology",
                     "alternateName": ["Tehran Polytechnic", "دانشگاه صنعتی امیرکبیر"]},
        "sameAs": ["https://github.com/Mahbodbe", "https://www.linkedin.com/in/mahbod-bemanicham-048b252ab",
                   "https://t.me/Mb_Mb84"],
        "knowsAbout": ["Embedded Systems", "Digital Design", "FPGA", "VHDL", "ESP32", "Control Systems",
                       "SCADA", "IEC 61850", "DNP3", "Intrusion Detection", "OT Security", "Qt", "Django"],
    }


# ───────────────────────── fragments ─────────────────────────
def card_html(r, lang):
    dot = LANG_COLORS.get(r.get("language") or "", "")
    topics = "".join(f"<li>{esc(x)}</li>" for x in (r.get("topics") or [])[:4])
    pinned = r["name"] in CFG["pinned"]
    body = r.get("excerpt") or r.get("description") or ""
    flag = '<span class="flag-pin" title="featured">★</span>' if pinned else ""
    style = f' style="--lang-dot:{dot}"' if dot else ""
    lang_html = (f'<span class="pcard__lang"><i aria-hidden="true"></i>{esc(r["language"])}</span>'
                 if r.get("language") else "<span></span>")
    upd = STR[lang]["rel_updated"]
    return (f'<a class="pcard" href="{esc(r["url"])}" target="_blank" rel="noreferrer" '
            f'data-repo="{esc(r["full_name"])}"{style}>'
            f'<div class="pcard__top"><span class="pcard__name">{esc(r["name"])} {flag}</span>'
            f'<span class="pcard__go" aria-hidden="true">↗</span></div>'
            f'<p class="pcard__excerpt">{esc(body) or "&nbsp;"}</p>'
            + (f'<ul class="pcard__topics">{topics}</ul>' if topics else "")
            + f'<div class="pcard__foot">{lang_html}<span title="stars">★ {r.get("stars", 0)}</span>'
              f'<span title="forks">⑂ {r.get("forks", 0)}</span><span class="pcard__spacer"></span>'
              f'<span>{esc(upd)} {esc(rel_time(r.get("pushed_at"), lang))}</span></div></a>')


def grid_html(lang):
    repos = [r for r in SNAP.get("repos", []) if r["name"] not in CFG["hidden"]]
    return "\n".join("        " + card_html(r, lang) for r in repos)


def featured_html(lang):
    out = []
    for slug in CFG["pinned"]:
        pj = PROJECTS.get(slug)
        if not pj:
            continue
        c = pj[lang]
        topics = "".join(f"<li>{esc(x)}</li>" for x in pj["stack"][:4])
        summary = c["summary"].split(". ")[0].rstrip(".") + "."
        out.append(
            f'        <a class="pcard pcard--page" href="{prefix(lang)}/projects/{sl(slug)}/">'
            f'<div class="pcard__top"><span class="pcard__name">{esc(c["title"])}</span>'
            f'<span class="pcard__go" aria-hidden="true">→</span></div>'
            f'<p class="pcard__excerpt">{esc(summary)}</p><ul class="pcard__topics">{topics}</ul>'
            f'<div class="pcard__foot"><span class="pcard__lang"><i aria-hidden="true"></i>{esc(pj["kind"])}</span>'
            f'<span class="pcard__spacer"></span><span>{esc(STR[lang]["read_more"])}</span></div></a>')
    return "\n".join(out)


def fill_i18n(page, lang):
    s = STR[lang]

    def sub_text(m):
        key = m.group("key")
        if key not in s or not isinstance(s[key], str):
            raise KeyError(f"missing i18n key: {key}")
        return f'<{m.group("tag")}{m.group("attrs")}>{s[key]}</{m.group("tag")}>'

    page = re.sub(r'<(?P<tag>[a-zA-Z0-9]+)(?P<attrs>[^<>]*?\sdata-i18n="(?P<key>[^"]+)"[^<>]*)>(?P<inner>.*?)</(?P=tag)>',
                  sub_text, page, flags=re.S)

    def sub_ph(m):
        tag = m.group(0)
        key = re.search(r'data-i18n-ph="([^"]+)"', tag).group(1)
        return re.sub(r'placeholder="[^"]*"', f'placeholder="{esc(s[key])}"', tag)

    page = re.sub(r"<input[^>]*data-i18n-ph=[^>]*>", sub_ph, page)
    return page


# ───────────────────────── pages ─────────────────────────
def build_home(lang):
    s = STR[lang]
    other = "fa" if lang == "en" else "en"
    tpl = rd("src", "template.html")
    stats = SNAP.get("stats", {})
    stars = sum(r.get("stars", 0) for r in SNAP.get("repos", []) if r["name"] not in CFG["hidden"])
    sync = ""
    if SYNC_DAY:
        sync = s["sync_note_fmt"].replace("{d}", SYNC_DAY)
    rep = {
        "{{LANG}}": lang, "{{DIR}}": s["dir"], "{{BODYCLASS}}": "fa-mode" if lang == "fa" else "",
        "{{ALT_HREF}}": "/fa/" if lang == "en" else "/", "{{ALT_LANG}}": other,
        "{{SWITCH_ARIA}}": esc(s["switch_language"]),
        "{{EN_ACTIVE}}": " is-active" if lang == "en" else "", "{{FA_ACTIVE}}": " is-active" if lang == "fa" else "",
        "{{ALT_HERO}}": esc(s["alt_hero"]), "{{ALT_W1}}": esc(s["alt_w1"]), "{{ALT_W2}}": esc(s["alt_w2"]),
        "{{OPEN_W1}}": esc(s["open_w1"]), "{{OPEN_W2}}": esc(s["open_w2"]),
        "{{STAT_REPOS}}": str(stats.get("repos", "—")), "{{STAT_STARS}}": str(stars),
        "{{STAT_FOLLOWERS}}": str(stats.get("followers", "—")), "{{STAT_SINCE}}": str(stats.get("since", "—")),
        "{{SYNCNOTE}}": esc(sync or s["sync_pending"]),
        "{{FEATURED}}": featured_html(lang), "{{GRID}}": grid_html(lang),
    }
    for k, v in rep.items():
        tpl = tpl.replace(k, v)
    tpl = fill_i18n(tpl, lang)

    canonical = home_url(lang)
    alternates = [("en", home_url("en")), ("fa", home_url("fa")), ("x-default", home_url("en"))]
    graph = {"@context": "https://schema.org", "@graph": [
        {"@type": "WebSite", "@id": f"{SITE}/#website", "url": f"{SITE}/", "name": NAME_EN,
         "alternateName": NAME_FA, "inLanguage": ["en", "fa"], "publisher": {"@id": f"{SITE}/#person"}},
        {"@type": "ProfilePage", "@id": canonical + "#profile", "url": canonical, "name": s["meta_title"],
         "description": s["meta_desc"], "inLanguage": lang, "isPartOf": {"@id": f"{SITE}/#website"},
         "mainEntity": {"@id": f"{SITE}/#person"}, "dateModified": HOME_LASTMOD,
         "primaryImageOfPage": {"@type": "ImageObject", "url": OG_IMAGE}},
        person(lang)]}
    hd = head(lang, s["meta_title"], s["meta_desc"], canonical, alternates, graph, og_alt=s["alt_hero"])
    tpl = tpl.replace("{{HEAD}}", hd)
    tpl = tpl.replace("{{LANG}}", lang)  # script src
    assert "{{" not in tpl, re.findall(r"\{\{[A-Z_0-9]+\}\}", tpl)
    wr("index.html" if lang == "en" else "fa/index.html", tpl)


PAGE_TPL = """<!DOCTYPE html>
<html lang="{lang}" dir="{dir}" data-theme="cobalt">
<head>
{head}
</head>
<body class="{bodyclass}">
<header class="nav">
  <div class="shell nav__inner">
    <a class="wordmark" href="{home}"><span>{brand}</span><span class="wordmark__dot" aria-hidden="true"></span></a>
    <nav class="nav__links" aria-label="Sections">
      <a class="nav__link" href="{home}#work">{nav_work}</a>
      <a class="nav__link" href="{home}#about">{nav_about}</a>
      <a class="nav__link" href="{home}#contact">{nav_contact}</a>
    </nav>
    <div class="nav__actions">
      <a class="lang-toggle" href="{alt_href}" hreflang="{alt_lang}" lang="{alt_lang}" aria-label="{switch}"><span class="lang-opt{en_a}">EN</span><span class="lang-sep">/</span><span class="lang-opt{fa_a}">فا</span></a>
    </div>
  </div>
</header>
<main>
{body}
</main>
<footer class="band"><div class="shell colophon"><p class="colophon__text">{footer}</p><div class="colophon__meta"><a class="link label" href="{home}">{home_label}</a><a class="link label" href="https://github.com/Mahbodbe" target="_blank" rel="noreferrer">GitHub</a></div></div></footer>
</body>
</html>
"""


def page_shell(lang, head_html, body, alt_href):
    s = STR[lang]
    other = "fa" if lang == "en" else "en"
    return PAGE_TPL.format(
        lang=lang, dir=s["dir"], head=head_html, bodyclass="fa-mode" if lang == "fa" else "",
        home=f"{prefix(lang)}/" or "/", brand=s["brand"], nav_work=s["nav_work"], nav_about=s["nav_about"],
        nav_contact=s["nav_contact"], alt_href=alt_href, alt_lang=other, switch=esc(s["switch_language"]),
        en_a=" is-active" if lang == "en" else "", fa_a=" is-active" if lang == "fa" else "",
        body=body, footer=s["footer_text"], home_label=s["home"])


def build_project(slug, lang):
    s = STR[lang]
    pj = PROJECTS[slug]
    c = pj[lang]
    canonical = proj_url(lang, slug)
    repo_url = f"https://github.com/Mahbodbe/{pj['repo']}"
    title = f'{c["title"]} | {s["brand"]}'
    alternates = [("en", proj_url("en", slug)), ("fa", proj_url("fa", slug)), ("x-default", proj_url("en", slug))]
    graph = {"@context": "https://schema.org", "@graph": [
        {"@type": "SoftwareSourceCode", "@id": canonical + "#code", "name": c["title"], "description": c["summary"],
         "codeRepository": repo_url, "programmingLanguage": pj["lang"], "inLanguage": lang,
         "url": canonical, "author": {"@id": f"{SITE}/#person"}, "keywords": ", ".join(pj["stack"])},
        {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": s["home"], "item": home_url(lang)},
            {"@type": "ListItem", "position": 2, "name": s["nav_work"], "item": home_url(lang) + "#work"},
            {"@type": "ListItem", "position": 3, "name": c["title"], "item": canonical}]},
        person(lang)]}
    hd = head(lang, title, c["summary"], canonical, alternates, graph, og_type="article", og_alt=c["title"])
    points = "".join(f"<li>{esc(x)}</li>" for x in c["points"])
    body = f"""<section class="band proj-head"><div class="shell">
  <ol class="crumbs"><li><a href="{prefix(lang)}/">{esc(s['home'])}</a></li><li><a href="{prefix(lang)}/#work">{esc(s['nav_work'])}</a></li><li aria-current="page">{esc(pj['repo'])}</li></ol>
  <p class="label">{esc(pj['kind'])}</p>
  <h1>{esc(c['title'])}</h1>
  <p class="lede">{esc(c['summary'])}</p>
  <dl class="facts">
    <div><dt>{esc(s['page_stack'])}</dt><dd>{esc(' · '.join(pj['stack']))}</dd></div>
    <div><dt>{esc(s['page_team'])}</dt><dd>{esc(c['team'])}</dd></div>
    <div><dt>{esc(s['page_kind'])}</dt><dd>{esc(pj['kind'])}</dd></div>
  </dl>
</div></section>
<section class="band section"><div class="shell">
  <h2 class="section__title">{esc(s['page_highlights'])}</h2>
  <ul class="proj-list prose">{points}</ul>
  <h2 class="section__title">{esc(s['page_role'])}</h2>
  <div class="prose"><p>{esc(c['role'])}</p></div>
  <div class="proj-actions"><a class="btn-solid" href="{repo_url}" target="_blank" rel="noreferrer">{esc(s['view_repo'])} <span aria-hidden="true">↗</span></a><a class="cta-type" href="{prefix(lang)}/#work">{esc(s['back_projects'])} <span aria-hidden="true">→</span></a></div>
</div></section>"""
    alt = f"{prefix('fa' if lang == 'en' else 'en')}/projects/{sl(slug)}/"
    wr(f"{prefix(lang).strip('/')}/projects/{sl(slug)}/index.html".lstrip("/"), page_shell(lang, hd, body, alt))


def build_404():
    lang = "en"
    s = STR[lang]
    hd = head(lang, f'{s["nf_title"]} | {NAME_EN}', s["nf_text"], f"{SITE}/404.html", [], {"@context": "https://schema.org"},
              robots="noindex, follow", preload=False)
    body = f'<section class="band proj-head"><div class="shell"><h1>{esc(s["nf_title"])}</h1><p class="lede">{esc(s["nf_text"])}</p><div class="proj-actions"><a class="btn-solid" href="/">{esc(s["home"])}</a><a class="cta-type" href="/fa/">فارسی</a></div></div></section>'
    wr("404.html", page_shell(lang, hd, body, "/fa/"))


def build_sitemap():
    def entry(slug_path, lastmod, en_url, fa_url):
        loc = en_url if slug_path == "en" else fa_url
        return (f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lastmod}</lastmod>\n"
                f'    <xhtml:link rel="alternate" hreflang="en" href="{en_url}" />\n'
                f'    <xhtml:link rel="alternate" hreflang="fa" href="{fa_url}" />\n'
                f'    <xhtml:link rel="alternate" hreflang="x-default" href="{en_url}" />\n  </url>')
    rows = [entry("en", HOME_LASTMOD, home_url("en"), home_url("fa")),
            entry("fa", HOME_LASTMOD, home_url("en"), home_url("fa"))]
    for slug in CFG["pinned"]:
        if slug in PROJECTS:
            rows.append(entry("en", LASTMOD, proj_url("en", slug), proj_url("fa", slug)))
            rows.append(entry("fa", LASTMOD, proj_url("en", slug), proj_url("fa", slug)))
    wr("sitemap.xml", '<?xml version="1.0" encoding="UTF-8"?>\n'
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
       + "\n".join(rows) + "\n</urlset>\n")


def main():
    write_runtime()
    for lang in ("en", "fa"):
        build_home(lang)
        for slug in PROJECTS:
            build_project(slug, lang)
    build_404()
    build_sitemap()
    print("build ok:", HOME_LASTMOD)


if __name__ == "__main__":
    main()
